In [1]:
import torch

x = torch.empty(1) # array of size 1. Essentially a 1D vector
print(x)



tensor([1.1210e-44])


In [2]:
x = torch.empty(3) # 1D vector with 3 elements
print(x)



tensor([0., -0., 0.])


In [3]:
x = torch.empty(2, 3) # 2D vector with 2 rows and 3 columns
print(x)



tensor([[7.0065e-44, 8.1275e-44, 7.0065e-44],
        [7.2868e-44, 8.1275e-44, 7.2868e-44]])


In [4]:
# random values
# rand Returns a tensor filled with random numbers from a uniform 
# distribution on the interval [0, 1)
x = torch.rand(2, 2)
print(x)



tensor([[0.5977, 0.4992],
        [0.6851, 0.3114]])


In [5]:
# So, in essence torch.FloatTensor() and torch.empty() does the same 
# job of returning a tensor
# filled with garbage values of dtype torch.float32

# just like in numpy
x = torch.zeros(2,2)
print(x)



tensor([[0., 0.],
        [0., 0.]])


In [6]:
x = torch.ones(2,2)
print(x)



tensor([[1., 1.],
        [1., 1.]])


In [7]:
# give data type
x = torch.ones(2,2, dtype=torch.float16)
print(x)



tensor([[1., 1.],
        [1., 1.]], dtype=torch.float16)


In [8]:
# creating a tensor
x = torch.tensor([2.5, 0.1])
print("creating a tensor using tensor=",x)



creating a tensor using tensor= tensor([2.5000, 0.1000])


In [9]:
# creating a tensor
x = torch.Tensor([2.5, 0.1])
print("creating a tensor using Tensor=",x)



creating a tensor using Tensor= tensor([2.5000, 0.1000])


In [10]:
# creating a empty tensor
x = torch.tensor(())
print("creating a empty tensor using tensor=",x)



creating a empty tensor using tensor= tensor([])


In [11]:
# creating a empty tensor
x = torch.Tensor()
print("creating a empty tensor using Tensor=",x)



creating a empty tensor using Tensor= tensor([])


In [12]:
x = torch.Tensor(2,3)
print("creating a tensor using Tensor=",x)



creating a tensor using Tensor= tensor([[0.0000e+00, -0.0000e+00, 0.0000e+00],
        [-0.0000e+00, 1.5414e-44, 0.0000e+00]])


In [13]:
x = torch.empty(2,3)
print("creating a tensor using empty=",x)




creating a tensor using empty= tensor([[4.2914e-05, 1.0027e-11, 1.1210e-44],
        [0.0000e+00, 5.2387e-08, 4.0371e-08]])


In [14]:
# https://stackoverflow.com/questions/51911749/what-is-the-difference-between-torch-tensor-and-torch-tensor
# https://stackoverflow.com/questions/51129043/whats-the-difference-between-torch-tensor-vs-torch-empty-in-pytorch

# torch.Tensor() is just an alias to torch.FloatTensor() which is the
# default type of tensor, when no dtype is specified during tensor construction.

# From the torch for numpy users notes, it seems that torch.Tensor() is a drop-in
# replacement of numpy.empty()

# So, in essence torch.FloatTensor() and torch.empty() does the same job of returning a
# tensor filled with garbage values of dtype torch.float32

# torch.empty() returns a tensor filled with uninitialized data. With arguments you can
# specify the shape of the tensor, the output tensor, the data type...

# This means you can create a tensor of floats, int... If no data type is specified then
# the chosen one is your default torch.Tensor type (which is torch.FloatTensor by default and
# you can change it using torch.set_default_tensor_type())

# torch.Tensor() is simply a special case of torch.empty() where the data type is torch.FloatTensor.


x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)



tensor([[0.8262, 0.9290],
        [0.9529, 0.8338]])
tensor([[0.4430, 0.5253],
        [0.0466, 0.3873]])


In [15]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)
y.add_(x) # in place
print(y)


tensor([[0.7452, 0.0748],
        [0.1752, 0.9012]])
tensor([[0.2468, 0.3845],
        [0.3233, 0.4436]])
tensor([[0.9921, 0.4592],
        [0.4985, 1.3448]])


In [16]:
# element wise addition
x = torch.tensor([
    [2, 2],
    [2, 2]
])

y = torch.tensor([
    [4, 4],
    [4, 4]
])
z = x + y
z = torch.add(x, y)
print(z)



tensor([[6, 6],
        [6, 6]])


In [17]:
# element wise subtraction
z = x - y
z = torch.sub(x, y)
print(z)



tensor([[-2, -2],
        [-2, -2]])


In [18]:
# element wise multiplication
z = x * y
z = torch.mul(x, y)
print(z)



tensor([[8, 8],
        [8, 8]])


In [19]:
# element wise division
z = x / y
z = torch.div(x, y)
print(z)

tensor([[0.5000, 0.5000],
        [0.5000, 0.5000]])


In [20]:
# slicing
x = torch.rand(5, 3)
print(x)

tensor([[0.1951, 0.5898, 0.1146],
        [0.4080, 0.9056, 0.8523],
        [0.0733, 0.7454, 0.4640],
        [0.9486, 0.2094, 0.9497],
        [0.7639, 0.2181, 0.2784]])


In [21]:
# iterating
for i, arr in enumerate(x):
    print(arr)

tensor([0.1951, 0.5898, 0.1146])
tensor([0.4080, 0.9056, 0.8523])
tensor([0.0733, 0.7454, 0.4640])
tensor([0.9486, 0.2094, 0.9497])
tensor([0.7639, 0.2181, 0.2784])


In [22]:
for i, arr in enumerate(x.numpy()):
    print(arr)

[0.19507903 0.58975446 0.1146391 ]
[0.4080456 0.9055868 0.8523062]
[0.07329142 0.745441   0.46401244]
[0.948641   0.20937026 0.94968826]
[0.76385707 0.21808952 0.2784117 ]


In [23]:
print(x[:,0])

tensor([0.1951, 0.4080, 0.0733, 0.9486, 0.7639])


In [24]:
print(x[1,:])

tensor([0.4080, 0.9056, 0.8523])


In [25]:
print(x[1,1])

tensor(0.9056)


In [26]:
print(x[1,1].item()) # item can be used only when there is just one value

0.9055867791175842


In [27]:
# reshaping
x = torch.rand(4, 4)
print(x)

tensor([[0.0112, 0.8466, 0.1396, 0.2296],
        [0.8844, 0.7424, 0.5566, 0.1188],
        [0.1590, 0.0885, 0.3760, 0.8899],
        [0.1746, 0.0650, 0.4654, 0.4186]])


In [28]:
y = x.view(-1,8)
print(y)
print(y.size())

tensor([[0.0112, 0.8466, 0.1396, 0.2296, 0.8844, 0.7424, 0.5566, 0.1188],
        [0.1590, 0.0885, 0.3760, 0.8899, 0.1746, 0.0650, 0.4654, 0.4186]])
torch.Size([2, 8])


In [29]:
y = x.view(8,2)
print(y)
print(y.size())

tensor([[0.0112, 0.8466],
        [0.1396, 0.2296],
        [0.8844, 0.7424],
        [0.5566, 0.1188],
        [0.1590, 0.0885],
        [0.3760, 0.8899],
        [0.1746, 0.0650],
        [0.4654, 0.4186]])
torch.Size([8, 2])


In [30]:
# numpy to tensor or vice versa
import numpy as np

In [31]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [32]:
b = a.numpy()
print(b)
print(type(b))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [33]:
# b and a share the same memory location. Be careful !. This happens when your tensor is on GPU

a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [34]:
a = np.ones(5)
b = torch.from_numpy(a)
print(b)
print(type(b))

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
<class 'torch.Tensor'>


In [35]:
# b and a share the same memory location. Be careful !. This happens when your tensor is on GPU
a += 1
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [36]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device= device) # this will create a tensor and put it on GPU.
    y = torch.ones(5)
    # now move it to GPU
    y = y.to(device)
    z = x + y # (will be performed in GPU) will be faster
    # z.numpy() # this will throw error
    z = z.to("cpu")
    # now we can do z.numpy() and it wont throw error.
else:
    print("cuda is not available")
    
    

cuda is not available


In [38]:
# This tells pytorch that later you need to calculate gradients for 
# this tensor. 
x = torch.ones(5, requires_grad= True)
print(x)


tensor([1., 1., 1., 1., 1.], requires_grad=True)
