In [3]:
import torch

x = torch.empty(1) # array of size 1. Essentially a 1D vector
print(x)

x = torch.empty(3) # 1D vector with 3 elements
print(x)

x = torch.empty(2, 3) # 2D vector with 2 rows and 3 columns
print(x)

# random values
# rand Returns a tensor filled with random numbers from a uniform distribution on the interval [0, 1)
x = torch.rand(2, 2)

# So, in essence torch.FloatTensor() and torch.empty() does the same job of returning a tensor
# filled with garbage values of dtype torch.float32

# just like in numpy
x = torch.zeros(2,2)
print(x)

x = torch.ones(2,2)
print(x)

# give data type
x = torch.ones(2,2, dtype=torch.float16)
print(x)

# creating a tensor
x = torch.tensor([2.5, 0.1])
print("creating a tensor using tensor=",x)

# creating a tensor
x = torch.Tensor([2.5, 0.1])
print("creating a tensor using Tensor=",x)

# creating a empty tensor
x = torch.tensor(())
print("creating a empty tensor using tensor=",x)

# creating a empty tensor
x = torch.Tensor()
print("creating a empty tensor using Tensor=",x)

x = torch.Tensor(2,3)
print("creating a tensor using Tensor=",x)

x = torch.empty(2,3)
print("creating a tensor using empty=",x)


# https://stackoverflow.com/questions/51911749/what-is-the-difference-between-torch-tensor-and-torch-tensor
# https://stackoverflow.com/questions/51129043/whats-the-difference-between-torch-tensor-vs-torch-empty-in-pytorch

# torch.Tensor() is just an alias to torch.FloatTensor() which is the
# default type of tensor, when no dtype is specified during tensor construction.

# From the torch for numpy users notes, it seems that torch.Tensor() is a drop-in
# replacement of numpy.empty()

# So, in essence torch.FloatTensor() and torch.empty() does the same job of returning a
# tensor filled with garbage values of dtype torch.float32

# torch.empty() returns a tensor filled with uninitialized data. With arguments you can
# specify the shape of the tensor, the output tensor, the data type...

# This means you can create a tensor of floats, int... If no data type is specified then
# the chosen one is your default torch.Tensor type (which is torch.FloatTensor by default and
# you can change it using torch.set_default_tensor_type())

# torch.Tensor() is simply a special case of torch.empty() where the data type is torch.FloatTensor.


x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)

# element wise addition
x = torch.tensor([
    [2, 2],
    [2, 2]
])

y = torch.tensor([
    [4, 4],
    [4, 4]
])
z = x + y
z = torch.add(x, y)
print(z)

# element wise subtraction
z = x - y
z = torch.sub(x, y)
print(z)

# element wise multiplication
z = x * y
z = torch.mul(x, y)
print(z)

# element wise division
z = x / y
z = torch.div(x, y)
print(z)

tensor([0.])
tensor([0.2112, 0.3457, 0.0561])
tensor([[ 0.0000e+00, -4.6566e-10,  1.2351e-36],
        [-2.8657e-42,  9.8091e-45,  1.3494e+00]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]], dtype=torch.float16)
creating a tensor using tensor= tensor([2.5000, 0.1000])
creating a tensor using Tensor= tensor([2.5000, 0.1000])
creating a empty tensor using tensor= tensor([])
creating a empty tensor using Tensor= tensor([])
creating a tensor using Tensor= tensor([[ 0.0000e+00, -4.6566e-10,  1.4801e-36],
        [-2.0005e+00,  5.6052e-45, -4.6566e-10]])
creating a tensor using empty= tensor([[0.0000e+00, 0.0000e+00, 2.5984e-36],
        [1.4013e-45, 9.1477e-41, 1.8750e+00]])
tensor([[0.8101, 0.6727],
        [0.8462, 0.8817]])
tensor([[0.5531, 0.8195],
        [0.2186, 0.3460]])
tensor([[6, 6],
        [6, 6]])
tensor([[-2, -2],
        [-2, -2]])
tensor([[8, 8],
        [8, 8]])
tensor([[0.5000, 0.5000],
        [0.5000, 0.50

In [4]:
# slicing
x = torch.rand(5, 3)
print(x)

tensor([[0.6204, 0.6500, 0.9651],
        [0.8387, 0.7962, 0.9675],
        [0.6082, 0.3435, 0.3799],
        [0.8086, 0.6633, 0.8338],
        [0.9937, 0.0318, 0.9508]])


In [6]:
print(x[:,0])

tensor([0.6204, 0.8387, 0.6082, 0.8086, 0.9937])


In [7]:
print(x[1,:])

tensor([0.8387, 0.7962, 0.9675])


In [8]:
print(x[1,1])

tensor(0.7962)


In [10]:
print(x[1,1].item()) # item can be used only when there is just one value

0.7962329983711243


In [11]:
# reshaping
x = torch.rand(4, 4)
print(x)

tensor([[0.0417, 0.4270, 0.5509, 0.1459],
        [0.1190, 0.7409, 0.9646, 0.1834],
        [0.0961, 0.5569, 0.1444, 0.2674],
        [0.5877, 0.3602, 0.6278, 0.3612]])


In [12]:
y = x.view(-1,8)
print(y)
print(y.size())

tensor([[0.0417, 0.4270, 0.5509, 0.1459, 0.1190, 0.7409, 0.9646, 0.1834],
        [0.0961, 0.5569, 0.1444, 0.2674, 0.5877, 0.3602, 0.6278, 0.3612]])
torch.Size([2, 8])


In [13]:
y = x.view(8,2)
print(y)
print(y.size())

tensor([[0.0417, 0.4270],
        [0.5509, 0.1459],
        [0.1190, 0.7409],
        [0.9646, 0.1834],
        [0.0961, 0.5569],
        [0.1444, 0.2674],
        [0.5877, 0.3602],
        [0.6278, 0.3612]])
torch.Size([8, 2])


In [14]:
# numpy to tensor or vice versa
import numpy as np

In [15]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [16]:
b = a.numpy()
print(b)
print(type(b))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [18]:
# b and a share the same memory location. Be careful !. This happens when your tensor is on GPU

a.add_(1)
print(a)
print(b)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


In [19]:
a = np.ones(5)
b = torch.from_numpy(a)
print(b)
print(type(b))

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
<class 'torch.Tensor'>


In [20]:
# b and a share the same memory location. Be careful !. This happens when your tensor is on GPU
a += 1
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [22]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device= device) # this will create a tensor and put it on GPU.
    y = torch.ones(5)
    # now move it to GPU
    y = y.to(device)
    z = x + y # (will be performed in GPU) will be faster
    # z.numpy() # this will throw error
    z = z.to("cpu")
    # now we can do z.numpy() and it wont throw error.
else:
    print("cuda is not available")
    
    

cuda is not available


In [24]:
# This tells pytorch that later you need to calculate gradients for this tensor. 
x = torch.ones(5, requires_grad= True)
print(x)


tensor([1., 1., 1., 1., 1.], requires_grad=True)
